els-ASAP auto commit file/tag pacemaker-1.1.18-3.el6.src.rpm

diff --git a/src/extra/resources/ifspeed b/src/extra/resources/ifspeed
--- a/src/extra/resources/ifspeed
+++ b/src/extra/resources/ifspeed
@@ -1,14 +1,19 @@
 #!/bin/bash
 #
 # OCF resource agent which monitors state of network interface and records it
-# as a value in CIB based on summ of speeds of its active (up, link detected,
-# not blocked) underlying interfaces.
+# as a node attribute in the CIB based on the sum of speeds of its active (up,
+# link detected, not blocked) underlying interfaces.
 #
 # Copyright (c) 2011 Vladislav Bogdanov <bubble@hoster-ok.com>
 # Partially based on 'ping' RA by Andrew Beekhof
 #
+# Change on 2017 by Tomer Azran <tomerazran@gmail.com>:
+#     Add "ip" parameter to detect network interface name by ip address:
+#     http://lists.clusterlabs.org/pipermail/users/2017-August/006224.html
+#
 # OCF instance parameters:
 #    OCF_RESKEY_name:         name of attribute to set in CIB
+#    OCF_RESKEY_ip            ip address to check
 #    OCF_RESKEY_iface:        network interface to monitor
 #    OCF_RESKEY_bridge_ports: if not null and OCF_RESKEY_iface is a bridge, list of
 #                             bridge ports to consider.
@@ -19,8 +24,16 @@
 # Initialization:
 
 : ${OCF_FUNCTIONS=${OCF_ROOT}/resource.d/heartbeat/.ocf-shellfuncs}
-. ${OCF_FUNCTIONS}
+
+# If these aren't available, we can still show help,
+# which is all that is needed to build the man pages.
+[ -r "${OCF_FUNCTIONS}" ] && . "${OCF_FUNCTIONS}"
+[ -r "${OCF_FUNCTIONS_DIR}/findif.sh" ] && . "${OCF_FUNCTIONS_DIR}/findif.sh"
+: ${OCF_SUCCESS=0}
+
 : ${__OCF_ACTION=$1}
+
+FINDIF=findif
 
 # Defaults
 OCF_RESKEY_name_default="ifspeed"
@@ -55,14 +68,14 @@ Examples:
 
 For STP-enabled bridges this RA tries to some-how guess network topology and by
 default looks only on ports which are connected to upstream switch. This can be
-overriden by 'bridge_ports' parameter. Active interfaces in this case are those
+overridden by 'bridge_ports' parameter. Active interfaces in this case are those
 in "forwarding" state.
 
 For balancing bonds this RA summs speeds of underlying "up" slave interfaces
 (and applies coefficient 0.8 to result).
 
-For non-balancing bonds ('active-backup' and probably 'brodcast') only speed of
-now active slave is used. 
+For non-balancing bonds ('active-backup' and probably 'broadcast'), only the
+speed of the currently active slave is used. 
 </longdesc>
 <shortdesc lang="en">Network interface speed monitor</shortdesc>
 
@@ -82,6 +95,17 @@ Network interface to monitor.
 </longdesc>
 <shortdesc lang="en">Network interface</shortdesc>
 <content type="string" default=""/>
+</parameter>
+
+<parameter name="ip" unique="0" required="0">
+<longdesc lang="en">
+Try to detect interface name by detecting the interface that holds the IP address.
+The IPv4 (dotted quad notation) or IPv6 address (colon hexadecimal notation)
+example IPv4 "192.168.1.1".
+example IPv6 "2001:db8:DC28:0:0:FC57:D4C8:1FFF".
+</longdesc>
+<shortdesc lang="en">IPv4 or IPv6 address</shortdesc>
+<content type="string" default="" />
 </parameter>
 
 <parameter name="bridge_ports" unique="0">
@@ -165,13 +189,38 @@ monitor() {
     return ${ret}
 }
 
+# This function tries to guess nic interface by IP
+get_nic_name_by_ip(){
+    # $FINDIF takes its parameters from the environment.
+    # Its output is as follows:
+    # [NIC_NAME] netmask [NETMASK] broadcast [BROADCAST}
+    NICINFO=$( ${FINDIF} )
+    rc=$?
+    if [ $rc -eq 0 ];then
+        # Get NIC_NAME part of findif function output.
+        echo "${NICINFO%% *}"
+    else
+        echo ""
+    fi
+}
+
 validate() {
     # Check the interface parameter
-    if [ -z "${OCF_RESKEY_iface}" ]; then 
-        ocf_log err "Empty iface parameter.  Please specify network interface to check"
-        exit $OCF_ERR_CONFIGURED
+    if [ -z "${OCF_RESKEY_iface}" ]; then
+        if [ -z "${OCF_RESKEY_ip}" ]; then
+            ocf_log err "Empty iface and ip parameters. Please specify either an interface name or valid ip address."
+            exit $OCF_ERR_CONFIGURED
+        else
+            ipcheck_ipv4 "${OCF_RESKEY_ip}"
+            if [ $? -eq 1 ] ; then
+                ipcheck_ipv6 "${OCF_RESKEY_ip}"
+                if [ $? -eq 1 ] ; then
+                  ocf_exit_reason "ip parameter [${OCF_RESKEY_ip}] is not a valid ip address."
+                  exit $OCF_ERR_CONFIGURED
+                fi
+            fi
+        fi
     fi
-
     return $OCF_SUCCESS
 }
 
@@ -204,6 +253,8 @@ iface_get_speed() {
             bond_get_speed ${iface}
         elif iface_is_vlan ${iface} ; then
             iface_get_speed $( vlan_get_phy ${iface} )
+        elif iface_is_hfi1 "${iface}" ; then
+            hfi1_get_speed "${iface}"
         else
             read speed < "/sys/class/net/${iface}/speed"
             echo ${speed}
@@ -224,6 +275,12 @@ iface_is_bridge() {
 iface_is_bond() {
     local iface=$1
     [ -e "/sys/class/net/${iface}/bonding" ] && return 0 || return 1
+}
+
+iface_is_hfi1() {
+    local iface=$1
+    driver=$(readlink /sys/class/net/${iface}/device/driver)
+    [[ $(basename ${driver}) =~ "hfi1" ]] && return 0 || return 1
 }
 
 vlan_get_phy() {
@@ -325,6 +382,23 @@ bridge_get_speed() {
     fi
 }
 
+hfi1_get_speed() {
+    local iface=$1
+    local hfi1_speed
+    local hfi1_value
+    local hfi1_desc
+
+    # Currently (9/14/2017 Intel Omni Path v10.5.0.0.155) Intel doesn't have Dual/Multiple ports Host Channel Adapters
+    # and it's save to use such method to get a speed.
+    # Example of output:
+    # [root@es-host0 ~]# cat /sys/class/net/ib0/device/infiniband/*/ports/*/rate
+    # 100 Gb/sec (4X EDR)
+    read hfi1_speed hfi1_value hfi1_desc < /sys/class/net/${iface}/device/infiniband/*/ports/*/rate
+    
+    # hfi1_value always in Gb/sec, so we need to convert hfi1_speed in Mb/sec
+    echo $(( hfi1_speed * 1000 ))
+}
+
 bond_get_slaves() {
     local iface=$1
     local slaves
@@ -392,7 +466,16 @@ bond_get_speed() {
 }
 
 update() {
-    local speed=$( iface_get_speed ${OCF_RESKEY_iface} )
+    local speed;
+    local nic=${OCF_RESKEY_iface};
+    if [ -z "${OCF_RESKEY_iface}" ]; then
+        nic=$( get_nic_name_by_ip )
+        if [ -z "${nic}" ];then
+            ocf_log err "Could not retrieve network interface name from ip address (${OCF_RESKEY_ip})"
+            exit $OCF_ERR_GENERIC
+        fi
+    fi
+    speed=$( iface_get_speed ${nic} )
 
     : $(( score = speed * ${OCF_RESKEY_weight_base} / 1000 ))
     if [ "$__OCF_ACTION" = "start" ] ; then
